FlowerDelivery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('website/', include('website.urls')),
    path('', RedirectView.as_view(url='website/', permanent=True)),
]

website/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),  # Главная страница
    path('register/', views.register, name='register'),  # Страница регистрации
    path('login/', views.login_view, name='login'),  # Страница входа
    path('logout/', views.logout_view, name='logout'),  # Функция для выхода
    path('showcase/', views.showcase, name='showcase'),  # Страница витрины/каталога для заказчиков
    path('cart/', views.cart, name='cart'),  # Страница корзины для заказа
    path('orders/', views.order_history, name='orders'),  # Страница истории заказов
    path('adminka/', views.login_admin, name='adminka'),  # Страница входа администратора
    path('home_admin/', views.home_admin, name='home_admin'),  # Страница администратора
]

website/models.py
from django.db import models
from django.urls import reverse


# 1. Заказчики
class Customer(models.Model):
    name = models.CharField(verbose_name='Имя', max_length=100)
    email = models.EmailField(verbose_name='Электронная почта', unique=True)
    phone = models.CharField(verbose_name='Телефон', max_length=20, blank=True, null=True)
    delivery_address = models.TextField(verbose_name='Адрес' )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('user_detail', args=[str(self.id)])

    class Meta:
        verbose_name = 'заказчик'
        verbose_name_plural = 'Заказчики'


# 2. Продукты
class Product(models.Model):
    name = models.CharField(verbose_name='Цветок', max_length=200)
    price = models.DecimalField(verbose_name='Цена', max_digits=10, decimal_places=2)
    image = models.ImageField(verbose_name='Изображение', upload_to='static/website/img/')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product_detail', args=[str(self.id)])

    class Meta:
        verbose_name = 'цветок'
        verbose_name_plural = 'Цветы'


# 3. Корзина заказчика
class Cart(models.Model):
    customer = models.ForeignKey(Customer, verbose_name='Заказчик', on_delete=models.CASCADE)
    delivery_address = models.TextField(verbose_name='Адрес')
    comment = models.TextField(verbose_name='Комментарии', blank=True, null=True)
    total_price = models.DecimalField(verbose_name='Стоимость', max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(verbose_name='Дата', auto_now_add=True)

    def __str__(self):
        return f"№{self.id}"

    def get_items_display(self):
        return ', '.join([f"{item.product.name}: {item.quantity} шт." for item in self.items.all()])

    get_items_display.short_description = 'В корзине'

    class Meta:
        verbose_name = 'корзинн'
        verbose_name_plural = 'Корзины заказов'


# 3.1. Товары в корзине
class CartItem(models.Model):
    cart = models.ForeignKey(Cart, verbose_name='Корзина',  related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, verbose_name='Цветок в корзине',  on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='Количество')

    def __str__(self):
        return f"{self.product.name}: {self.quantity} шт."

    class Meta:
        verbose_name = 'цветок в корзине'
        verbose_name_plural = 'Цветы в корзинах'


# 4. История заказов
class OrderHistory(models.Model):
    STATUS_CHOICES = [
        ('ORDERED', 'Заказан'),
        ('RECEIVED', 'Получен'),
        ('CANCELED', 'Отменен'),
        ('PAID', 'Оплачен'),
    ]
    USER_CHOICES = [
        ('ORDERED', 'Заказан'),
        ('RECEIVED', 'Получен'),
        ('CANCELED', 'Отменен'),
    ]

    cart = models.OneToOneField(Cart, verbose_name='Корзина', on_delete=models.CASCADE)
    order_date = models.DateTimeField(verbose_name='Дата заказа', auto_now_add=True)
    cart_price = models.DecimalField(verbose_name='Стоит руб.', max_digits=10, decimal_places=2)
    status = models.CharField(verbose_name='Статус', max_length=10, choices=STATUS_CHOICES, default='ORDERED')

    def __str__(self):
        return f"Заказ {self.id} - {self.cart.customer.name}"

    class Meta:
        verbose_name = 'заказ'
        verbose_name_plural = 'Заказы'


class BotConfig(models.Model):
    bot_id = models.CharField(max_length=16, verbose_name='ID бота')

website/forms.py
from django import forms
from .models import Customer


class UserRegistrationForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ['name', 'email', 'phone', 'delivery_address']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'phone': forms.TextInput(attrs={'class': 'form-control'}),
            'delivery_address': forms.TextInput(attrs={'class': 'form-control'}),
        }


class LoginForm(forms.Form):
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Введите ваш email'}),
        error_messages={'required': 'Это поле обязательно для заполнения.'}
    )

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if not Customer.objects.filter(email=email).exists():
            raise forms.ValidationError('Пользователь с такой электронной почтой не найден.')
        return email


class LoginByEmailForm(forms.Form):
    email = forms.EmailField(label='Электронная почта', max_length=255)

    def clean_email(self):
        email = self.cleaned_data.get('email')
        return email


class DeliveryAddressForm(forms.Form):
    address = forms.CharField(
        label='Адрес доставки',
        max_length=255,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

website/views.py
import pytz
import json
import asyncio
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from django.views.decorators.cache import never_cache
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.http import JsonResponse
from .forms import UserRegistrationForm, LoginForm, LoginByEmailForm, DeliveryAddressForm
from .models import Customer, Product, Cart, CartItem, OrderHistory, BotConfig
from .telebot.message_to_bot import send_message
from .telegram_bot import send_initial_message
from django.core.cache import cache

TIME = (8, 23)  # время работы с 8:00 до 23:00
IS_OPEN = False


# Функция для отображения главной страницы
@never_cache
def home(request):
    global TIME
    time_open = TIME[0]
    time_close = TIME[1]

    local_time = timezone.now().astimezone(pytz.timezone('Europe/Moscow'))

    # Установим время начала и окончания работы
    start_time = local_time.replace(hour=time_open, minute=0, second=0, microsecond=0)
    end_time = local_time.replace(hour=time_close, minute=0, second=0, microsecond=0)

    global IS_OPEN
    IS_OPEN = start_time <= local_time <= end_time
    # IS_OPEN = True

    try:
        buyer = request.session['buyer']
        customer = get_object_or_404(Customer, name=buyer)
        carts = Cart.objects.filter(customer=customer)
        # Получаем все заказы, связанные с корзинами покупателем
        orders = OrderHistory.objects.filter(cart__in=carts)
        k_orders = orders.count()
    except KeyError:
        buyer = None
        k_orders = 0

    context = {
        'user': buyer,
        'k_orders': k_orders,
        'current_time': local_time.strftime('%H:%M'),
        'open': str(time_open),
        'close': str(time_close),
        'is_open': IS_OPEN  # Передаем информацию о доступности доставки
    }

    return render(request, 'website/home.html', context)


# Функция для отображения страницы регистрации
def register(request):
    if request.method == 'POST':  # Обработка POST-запроса
        form = UserRegistrationForm(request.POST)  # Инициализация формы
        if form.is_valid():  # Проверка формы
            form.save()  # Сохранение формы
            request.session['email'] = form.cleaned_data['email']  # запомнить email в сессии
            request.session['buyer'] = form.cleaned_data['name']  # запомнить имя пользователя в сессии

            return redirect('home')  # Перенаправление на домашнюю страницу
    else:
        form = UserRegistrationForm()  # Инициализация формы
    # Отображение формы
    return render(request, 'website/register.html', {'form': form, 'is_open': IS_OPEN})


# Функция для отображения страницы входа
def login_view(request):
    if request.method == 'POST':  # Обработка POST-запроса
        form = LoginForm(request.POST)  # Инициализация формы
        if form.is_valid():
            email = form.cleaned_data['email']  # Получить email из формы
            buyer = get_object_or_404(Customer, email=email)  # Поиск пользователя по email
            request.session['email'] = email  # запомнить email в сессии
            request.session['buyer'] = buyer.name  # запомнить имя пользователя в сессии
            return redirect('home')  # Перенаправление на страницу каталога
    else:
        form = LoginForm()  # Инициализация формы

    # Отображение формы
    return render(request, 'website/login.html', {'form': form, 'is_open': IS_OPEN})


# Функция для выхода
def logout_view(request):
    # Очистить конкретные данные
    request.session.pop('email', None)
    request.session.pop('buyer', None)
    request.session.pop('selected_products', None)
    request.session.pop('cart_id', None)
    return redirect('home')  # перенаправление на домашнюю страницу


# Функция для отображения страницы витрины
@never_cache
def showcase(request):
    buyer = request.session.get('buyer')
    if buyer:
        customer = get_object_or_404(Customer, name=buyer)
        delivery_address = customer.delivery_address
    else:
        delivery_address = None

    products = Product.objects.all()

    if buyer and request.method == 'POST':
        product_counts = {key.split('[')[1][:-1]: value for key, value in request.POST.items() if
                          key.startswith('product_counts')}
        total_price = 0
        valid_products = {}

        for product_id, count_str in product_counts.items():
            if count_str.strip().isdigit():
                count = int(count_str)
                if count > 0:
                    product = get_object_or_404(Product, id=int(product_id))
                    total_price += product.price * count
                    valid_products[product] = count

        if total_price > 0:
            new_cart = Cart.objects.create(
                customer=customer,
                delivery_address=delivery_address,
                comment='',
                total_price=total_price,
                created_at=timezone.now().astimezone(pytz.timezone('Europe/Moscow'))
            )

            CartItem.objects.bulk_create([
                CartItem(cart=new_cart, product=product, quantity=count) for product, count in valid_products.items()
            ])

            request.session['cart_id'] = new_cart.id
            return redirect('cart')  # Перенаправляем на страницу просмотра корзины заказчика

        return redirect('home')  # Перенаправляем на главную страницу когда корзина пуста

    context = {
        'products': products,
        'user': buyer
    }
    return render(request, 'website/showcase.html', context)


# Функция для отображения страницы заказанной корзины
def cart(request):
    carta = get_object_or_404(Cart, id=request.session.get('cart_id'))

    if carta is not None and request.method == 'POST':
        carta.delivery_address = request.POST.get('delivery_address')
        carta.comment = request.POST.get('comment')
        carta.save()  # Сохраняем обновленный адрес доставки и комментарии
        now_is = timezone.now().astimezone(pytz.timezone('Europe/Moscow'))
        new_order = OrderHistory.objects.create(
            cart=carta,
            order_date=now_is,
            cart_price=carta.total_price
        )
        new_order.save()

        buket = carta.get_items_display()
        text_for_bot = (f'{now_is.strftime("%H:%M %d.%m.%y")}\n{new_order}\n'
                        f'Букет: {buket}\n'
                        f'Сумма заказа: {new_order.cart_price}₽\n'
                        f'Адрес доставки: {carta.delivery_address}')
        if carta.comment != '':
            text_for_bot += f'\n{carta.comment}'
        # Отпраляем сообщение боту
        asyncio.run(send_initial_message(text_for_bot))

        return redirect('orders')

    # Если request.method == 'GET' то
    return render(request, 'website/cart.html', {'cart': carta})


# Функция для авторизации Админа
def login_admin(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('home_admin')  # Замените 'home' на вашу главную страницу
        else:
            messages.error(request, 'Неверное имя пользователя или пароль.')

    return render(request, 'website/login_admin.html')


# Функция для обновления статуса
def update_order_status(request):
    try:
        # Получаем данные из JSON-запроса
        data = json.loads(request.body)
        order_id = data.get('order_id')
        new_status = data.get('status')

        # Находим заказ по ID и обновляем статус
        order = OrderHistory.objects.get(id=order_id)
        order.status = new_status  # Предполагается, что status является полем модели
        order.save()
        text = f'\nСтатус заказа №{order_id} изменен на {order.get_status_display()}.'
        # send_message(text)
        asyncio.run(send_initial_message(text))
        # Возвращаем успешный ответ
        return JsonResponse({'status': 'success', 'new_status': order.get_status_display()})

    except OrderHistory.DoesNotExist:
        return JsonResponse({'status': 'error', 'message': 'Заказ не найден'}, status=404)
    except Exception as e:
        return JsonResponse({'status': 'error', 'message': str(e)}, status=500)


# Функция для отображения страницы истории заказов
def order_history(request):
    # Проверяем, авторизован ли пользователь
    try:
        buyer = request.session['buyer']
        customer = get_object_or_404(Customer, name=buyer)
        carts = Cart.objects.filter(customer=customer)  # Получаем все корзины покупателя
        # Получаем все заказы, связанные с корзинами покупателя
        orders = OrderHistory.objects.filter(cart__in=carts).order_by('-order_date')

        if request.method == 'POST':
            if 'repeat' in request.POST:  # Обработка нажатия кнопки "Повторить"
                order_id = request.POST.get('repeat')
                order = get_object_or_404(OrderHistory, id=order_id)
                carta = order.cart
                new_cart = Cart.objects.create(
                    customer=customer,
                    delivery_address=carta.delivery_address,
                    comment=carta.comment,
                    total_price=carta.total_price,
                    created_at=timezone.now().astimezone(pytz.timezone('Europe/Moscow'))
                )
                cart_items = carta.items.all()
                # Преобразуем в нужный формат данные из корзины
                products = [(item.product, item.quantity) for item in cart_items]
                # Обрабатываем выбранные продукты
                for product, count in products:
                    product_ = Product.objects.get(id=product.id)
                    # Создаем копию букета корзины

website/templates/website/cart.html
{% extends 'website/home.html' %}
{% load static %}

{% block content %}
<div class="container">
    <div class="registration-form">
        <form method="post" class="mt-4">
            {% csrf_token %}
            <h1>Оформление заказа</h1>
            <h3>Корзина {{ cart }}</h3>
            <h4>
            {% for item in cart.items.all %}
                {{ item.product.name }}: {{ item.quantity }} шт.,
            {% endfor %}
            </h4>
            <h4>Стоимость: {{ cart.total_price }} руб.</h4>

            <p>Дата заказа: {{ cart.created_at }}</p>

            <div class="form-group">
                <label for="id_address">Адрес доставки:</label>
                <input type="text" name="delivery_address" id="id_address" class="form-control"
                       value="{{ cart.customer.delivery_address }}" required>
            </div>

            <div class="form-group">
                <label for="id_comment">Комментарий:</label>
                <textarea name="comment" id="id_comment" class="form-control"></textarea>
            </div>
            <div>
                <p><button type="submit" class="btn btn-primary">Отправить заказ</button></p>
                <p><a class="btn btn-success"  href="{% url 'showcase' %}">Вернуться в каталог</a></p>
            </div>
        </form>
    </div>
</div>
{% endblock %}

website/templates/website/home.html
{% load static %}
<!--<!DOCTYPE html>-->
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'website/favicon.ico' %}" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'website/css/styles.css' %}">

    <title>Служба доставки цветов</title>
</head>
<body>
    <main class="home">
                {% block content %}
        <div class="container">
                    {% if is_open %}
            <div class="home-form">
                    {% else %}
            <div class="home-form" style="background: #ddd;">
                    {% endif %}
                <form method="post" class="mt-4" style="color: #a00;">
                    {% if is_open %}
                        <h1>Добро пожаловать в службу доставки цветов!</h1>
                        <p>Мы рады предложить вам широкий ассортимент свежих цветов и букетов для любого повода.</p>
                    {% else %}
                        <h1>Служба доставки цветов.</h1>
                    {% endif %}
                    {% if user is not None %}
                        <p><strong>{{ user }}, вы вошли на сайт</strong></p>
                        {% if k_orders > 0 %}
                            <p><a href="{% url 'orders' %}"><strong>Ваша история заказов</strong></a></p>
                        {% endif %}
                        <p><a href="{% url 'showcase' %}"><strong>Сделайте выбор цветов на странице "Витрина" указав количество</strong></a></p>
                        <p><a href="{% url 'logout' %}">Выход</a></p>
                    {% else %}
                        {% if is_open %}
                            <p><a href="{% url 'login' %}">Для начала войдите на страницу "Вход"</a></p>
                            <p><a href="{% url 'register' %}">или зарегистрируйтесь на странице "Регистация"</a></p>
                        {% endif %}
                        <p><a href="{% url 'showcase' %}">Посмотрите букеты на странице "Витрина"</a></p>
                    {% endif %}
                    <br>
                    <h5> Служба доставки цветов работает с {{open}}:00 до {{close}}:00 (мск)</h5>
                    <p>Сейчас <span id="current-time">{{ current_time }}</span></p></p>
                </form>
            </div>
        </div>
        <script>
            function updateTime() {
                const now = new Date();
                const hours = String(now.getHours()).padStart(2, '0');
                const minutes = String(now.getMinutes()).padStart(2, '0');
                document.getElementById('current-time').textContent = `${hours}:${minutes}`;
            }
            setInterval(updateTime, 10000); // Обновление каждые 10 секунд
            window.onload = updateTime; // Установка времени при загрузке страницы
        </script>
                {% endblock %}
    </main>

<!-- Подключение jQuery -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<!-- Подключение Bootstrap JS -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script></body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</html>

website/templates/website/home_admin.html
{% extends 'website/login_admin.html' %}
{% load static %}

{% block content %}
<div>
    <form method="post" class="mt-4">
        {% csrf_token %}
        <h1 style="text-align: center; color: #a00;">История заказов
            <a class="btn btn-success btn-lg" style="float: right;" href="{% url 'home' %}" role="button">Закрыть</a>
        </h1>
        <table class="table table-success table-striped" >
            <thead>
                <tr>
                    <th>№</th>
                    <th>Корзина</th>
                    <th>Дата</th>
                    <th>Статус</th>
                    <th>Стоимость</th>
                    <th>Букет</th>
                </tr>
            </thead>
            <tbody>
            {% for order in orders %}
            <tr>
                <td class="align-middle">{{ order.id }}</td>
                <td class="align-middle">{{ order.cart }}</td>
                <td class="align-middle">{{ order.order_date|date:"d.m.Y" }}</td>
                <td>
                    <select class="form-select status-select" name="status" data-order-id="{{ order.id }}">
                        <option value="{{ order.status }}" selected>{{ order.get_status_display }}</option>
                        {% for choice in order.STATUS_CHOICES %}
                            <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                        {% endfor %}
                    </select>
                </td>
                <td class="align-middle">{{ order.cart_price }} руб.</td>
                <td class="align-middle">
                    {% for item in order.cart.items.all %}
                        {{ item.product.name }}: {{ item.quantity }} шт.,
                    {% endfor %}
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </form>
</div>

<script>
document.querySelectorAll('.status-select').forEach(select => {
    select.addEventListener('change', function() {
        const orderId = this.getAttribute('data-order-id');
        const newStatus = this.value;

        fetch("{% url 'home_admin' %}", {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': '{{ csrf_token }}'
            },
            body: JSON.stringify({
                order_id: orderId,
                status: newStatus
            })
        })
        .then(response => response.json())
        .then(data => {
            if (data.status === 'success') {
                console.log('Статус обновлен:', data.new_status);
            } else {
                console.error('Ошибка обновления статуса');
            }
        })
        .catch(error => console.error('Ошибка:', error));
    });
});

</script>
{% endblock %}

website/templates/website/login.html
{% extends 'website/home.html' %}
{% block content %}
<div class="container">
    <div class="registration-form">
        <h3 class="text-center">Вход на сайт</h3>
        <form method="post" class="mt-4">
            {% csrf_token %}
            <div class="mb-1">
                <label for="id_email">Ваша электронная почта?</label>
                {{ form.email }}
                {% if form.email.errors %}
                    <div class="text-danger">{{ form.email.errors }}</div>
                {% endif %}
            </div>
            <button type="submit" class="btn btn-primary">Войти</button>
        </form>
    </div>
</div>
{% endblock %}

website/templates/website/login_admin.html
{% load static %}
<!--<!DOCTYPE html>-->
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'website/favicon.ico' %}" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'website/css/styles.css' %}">

    <title>Страница администратора</title>
</head>
<body>
    <main class="login-page">
                {% block content %}
        <div class="container">
            <div class="registration-form">
                <h2>Вход администратора</h2>
                {% if messages %}
                    {% for message in messages %}
                        <div>{{ message }}</div>
                    {% endfor %}
                {% endif %}
                <form method="post"  class="mt-4">
                    {% csrf_token %}
                    <h5><label for="username">Имя пользователя:</label></h5>
                    <input type="text" id="username" name="username" required>
                    <h5><label for="password">Пароль:</label></h5>
                    <input type="password" id="password" name="password" required>
                    <p> </p>
                    <p><button type="submit" class="btn btn-primary">Войти</button></p>
                </form>
                {% endblock %}
            </div>
        </div>
    </main>
</body>
</html>

website/templates/website/order_history.html
{% extends 'website/home.html' %}
{% load static %}

{% block content %}
<div>
    <form method="post" class="mt-4">
        {% csrf_token %}
        <h1 style="text-align: center; color: #a00;">{{ user }}, ваша история заказов
            <a class="btn btn-success btn-lg" style="float: right;" href="{% url 'home' %}" role="button">Закрыть</a>
        </h1>
    <table class="table table-success table-striped" >
        <thead>
            <tr>
                <th>№</th>
                <th>Корзина</th>
                <th>Дата</th>
                <th>Статус</th>
                <th>Стоимость</th>
                <th>Букет</th>
                <th>Действие</th>
            </tr>
        </thead>
        <tbody>
        {% for order in orders %}
        <tr>
            <td class="align-middle">{{ order.id }}</td>
            <td class="align-middle">{{ order.cart }}</td>
            <td class="align-middle">{{ order.order_date|date:"d.m.Y" }}</td>
            <td class="align-middle">
                {% if order.status == 'PAID' %}
                    {{ order.get_status_display }}
                {% else %}
                    <select class="form-select status-select" name="status" data-order-id="{{ order.id }}">
                        <option value="{{ order.status }}" selected>{{ order.get_status_display }}</option>
                        {% for choice in order.USER_CHOICES %}
                            <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                        {% endfor %}
                    </select>
                {% endif %}
            </td>
            <td class="align-middle">{{ order.cart_price }} руб.</td>
            <td class="align-middle">
                {% for item in order.cart.items.all %}
                    {{ item.product.name }}: {{ item.quantity }} шт.,
                {% endfor %}
            </td>
            <td>
                <button class="btn btn-outline-primary" style="white-space:nowrap" type="submit" name="repeat" value="{{ order.id }}">
                    Повторить заказ
                </button>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    </form>
</div>

<script>
document.querySelectorAll('.status-select').forEach(select => {
    select.addEventListener('change', function() {
        const orderId = this.getAttribute('data-order-id');
        const newStatus = this.value;

        fetch("{% url 'orders' %}", {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': '{{ csrf_token }}'
            },
            body: JSON.stringify({
                order_id: orderId,
                status: newStatus
            })
        })
        .then(response => response.json())
        .then(data => {
            if (data.status === 'success') {
                console.log('Статус обновлен:', data.new_status);
            } else {
                console.error('Ошибка обновления статуса');
            }
        })
        .catch(error => console.error('Ошибка:', error));
    });
});

</script>
{% endblock %}

website/templates/website/register.html
{% extends 'website/home.html' %}
{% block content %}
<div class="container">
    <div class="registration-form">
        <form method="post" class="mt-4">
            <h2 class="mt-5">Регистрация пользователя</h2>
            <br>
            {% csrf_token %}
            <div class="form-group">
                <label for="id_name">Ваше имя:</label>
                {{ form.name }}
                {% if form.name.errors %}
                    <div class="text-danger">{{ form.name.errors }}</div>
                {% endif %}
            </div>
            <div class="form-group">
                <label for="id_email">Электронная почта:</label>
                {{ form.email }}
                {% if form.email.errors %}
                    <div class="text-danger">{{ form.email.errors }}</div>
                {% endif %}
            </div>
            <div class="form-group">
                <label for="id_phone">Номер телефона:</label>
                {{ form.phone }}
                {% if form.phone.errors %}
                    <div class="text-danger">{{ form.phone.errors }}</div>
                {% endif %}
            </div>
            <div class="form-group">
                <label for="id_address">Адрес доставки:</label>
                {{ form.delivery_address }}
                {% if form.delivery_address.errors %}
                    <div class="text-danger">{{ form.delivery_address.errors }}</div>
                {% endif %}
            </div>
            <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
        </form>
    </div>
</div>
{% endblock %}